name: flutter_gif
description: gif image widget help to control gif progress,speed,repeat frames .
version: 0.0.4
homepage: https://github.com/saytoonz/flutter_gif

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  crypto: any
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
